#========kFood========#
#Main config file of kFood.
#
#Values and extras can be
#changed in this config.
#=====================#

#NOTE: Many options are based on names wich are based on your server's locale.
#If you change the language on your server, be sure to update all names in this config aswell!

#========MAIN========#
#Run the plugin in debug mode?
debug: false

#Sets the default food value. (1-20)
#You can affect the diffculty of minecraft a bit here.
#If set below 7, players cannot run.
#If set above 17, players will always regenerate health.
default-food: 17
#Other plugins, admins or command blocks can change the default-food per player.

#Use potion mechanics for healing? (Regeneration II and Poison II)
#Usually the plugin just adds hearts or damages the player.
#When enabled, this option overrides this behaviour to instead
#just give the player potion effects.
#This result in the player healing more slowly and thus requiring
#him to wait before eating again. Players will receive Poison II if
#a negative value is given, so when true they can't die of eating anymore.
#Note: This value will override potion-effects.
potion-mechanics: false

#========Custom Items========#
#Should the plugin allow custom items (names)?
allow-custom: true
#Detect if a custom name came from an anvil? If set to true anvil items can be set using a_itemName.
detect-anvil: true
#When someone renamed their food in an anvil and no a_itemName is present below, revert back to the orginal item name?
revert-anvil: true

#========Effects========#
#Use potion effects to make healing a bit more showfull?
potion-effects: true 
#Should the player burb after eating an instant food?
burb-effect: true

#========Foods========#
#Consumables can be added here.
#Usage: 
# name: halfheartstoheal
#
#Supports custom items! (When allow-custom: true)
#Make sure that your custom item's name contains ChatColor.RESET to disable the italic text
#and ensure kFood doesn't see the item as being named by an anvil.
#
#Anvil items (when detect-anvil: true) can be added in aswell.
#Usage:
# a_name: halfhearts to heal.
foods:
 Apple: 2.0
 Baked Potato: 3.0
 Beetroot: 1.0
 Beetroot Soup: 6.0
 Bread: 3.0
 Carrot: 2.0
 Chorus Fruit: 4.0
 Tropical Fish: 1.0
 Cooked Chicken: 5.0
 Cooked Cod: 5.0
 Cooked Mutton: 6.0
 Cooked Porkchop: 8.0
 Cooked Rabbit: 6.0
 Cooked Salmon: 6.0
 Cookie: 2.0
 Golden Apple: 4.0
 Golden Carrot: 6.0
 Melon: 1.0
 Mushroom Stew: 6.0
 Poisonous Potato: -3.0
 Potato: 1.0
 Pufferfish: -1.0
 Pumpkin Pie: 8.0
 Rabbit Stew: 9.0
 Raw Beef: 3.0
 Raw Chicken: -2.0
 Raw Cod: 2.0
 Raw Mutton: 2.0
 Raw Porkchop: 3.0
 Raw Rabbit: 2.0
 Raw Salmon: 4.0
 Rotten Flesh: -1.0
 Spider Eye: -5.0
 Steak: 8.0
 Dried Kelp: 1.0
 
#Custom item examples:
#Let's say a different plugin adds in the recipe for a sandwich,
#the display name of this item is "Sandwich". We want the player to receive 3 harts.
# Sandwich: 6.0
#
#When you put a piece of bread in a anvil and try to give it the name Sandwich,
#it obviously isn't the real thing. We want the player be punished if he eats the fake sandwich.
# a_Sandwich: -5.0

#========Instant Foods========#
#Foods that can be eaten instantly.
#Usage:
# name: halfheartstoheal
#
#Supports same behaviour as the regular foods.
#If you want every food to be eaten instantly, cut the contents
#from the foods: catagory and paste them here.
#
#Unlike foods:, instant-foods support non-consumable items.
instant-foods:
 Sugar: 1.0

#========Misc========#
#The cake is a speciality and handled a bit differently.
#This value corresponds to the halfhearts healed for each slice. (note: A cake has seven slices)
cake: 2.0

#When an instant-food is eaten that contains one of these strings, a bowl is returned.
#To disable simply remove all entries. (But leave return-bowl: intact!)
return-bowl:
 - Stew
 - Soup